# -*- coding: utf-8 -*-
"""matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBoamlYHHhtM5Hyb3EA7PxEEOeNiMyI4
"""

!pip install numpy
import numpy as np
!pip install pandas
import pandas as pd
import matplotlib.pyplot as plt
import urllib.request
import os

# File URLs
male_data_url = "https://github.com/gagolews/teaching-data/raw/master/marek/nhanes_adult_male_bmx_2020.csv"
female_data_url = "https://github.com/gagolews/teaching-data/raw/master/marek/nhanes_adult_female_bmx_2020.csv"

# Load data into pandas DataFrames with error handling
try:
    male_data = pd.read_csv(male_data_url, on_bad_lines='skip')
    female_data = pd.read_csv(female_data_url, on_bad_lines='skip')
except pd.errors.ParserError as e:
    print("Error loading data:", e)
    raise

# Print column names to check their availability
print("Columns in Male Data:", male_data.columns)
print("Columns in Female Data:", female_data.columns)

# Verify column names and adjust if necessary
columns_to_select = ['BMXWT', 'BMXHT', 'BMXARML', 'BMXLEG', 'BMXARMC', 'BMXHIP', 'BMXWAIST']

# Check if required columns exist
missing_male_cols = [col for col in columns_to_select if col not in male_data.columns]
missing_female_cols = [col for col in columns_to_select if col not in female_data.columns]

if missing_male_cols:
    print(f"Missing columns in Male Data: {missing_male_cols}")
if missing_female_cols:
    print(f"Missing columns in Female Data: {missing_female_cols}")

# Display the first few rows of each dataset
print("Male Matrix (First 8 Rows):")
print(male_data[:8])

print("\nFemale Matrix (First 8 Rows):")
print(female_data[:8])

#Print the shapes to verify
print("Male Matrix Shape:", male_data.shape)
print("Female Matrix Shape:", female_data.shape)

